apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-80gy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-urxt-tenant/rhtap-demo-app/hacbs-test-project-80gy@sha256:a002983335bdac6273c2b2478aa625a7f4ab621f6107ed70e35d466c64be7658
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
